import React, {useEffect} from 'react';

export const FirstNestedComponent = () => {
  return (
    <div>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque consequuntur perferendis similique laboriosam iste ad. Qui neque iste obcaecati pariatur odit fugit at, eius quas in eligendi necessitatibus dolor exercitationem.</h1>
    </div>
  )
}